# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be4bc685c89a5968390195ead732fed623ec11f06ceba41d4258e5b7bb7ba4aa5e5d9370b40972c7b64a9a902f61ba55f3f8356c296e4b818c53ed90e9e2181

test:
  secret_key_base: ef93eb47a4c60c7472ff3593240225c6d52902ed5744fe25109b3f4a08582b78f21da6a15c009d63ce689f0e0ad67eceea71d34df71a163475eb0a4c012efa79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
